[fix] Add --purge
YunoHost-Apps/photoview_ynh pull request #20
Opened 2022-02-24 21:08 UTC by Galettofraise

## Problem

- *To add the option --purge*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-02-24 21:09 UTC, Jules-Bertholet requested changes

2022-02-24 21:09 UTC, Jules-Bertholet commented on scripts/remove
>  ynh_secure_remove --file="$data_path"
You need to get rid of this line

2022-02-24 21:18 UTC, Galettofraise commented on scripts/remove
>  ynh_secure_remove --file="$data_path"
Ok i fix that

2022-02-24 22:39 UTC, Jules-Bertholet approved these changes

2022-02-24 22:40 UTC, Jules-Bertholet commented
!testme

2022-02-27 20:14 UTC, zamentur approved these changes

2022-02-27 22:59 UTC, Jules-Bertholet approved these changes

2022-02-27 22:59 UTC, Jules-Bertholet commented
!testme

2022-03-01 01:44 UTC, yalh76 commented
`data_path` is checked during install ... that's why adding purge option doesn't work

2024-02-28 16:13 UTC, merged