Bullseye
YunoHost-Apps/photoview_ynh pull request #24
Opened 2022-04-05 23:16 UTC by yalh76

## Solution

- *Fix #19*
- *Apply last example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-04-05 23:16 UTC, yalh76 commented
!testme

2022-04-06 14:32 UTC, yalh76 commented
!testme

2022-04-07 03:49 UTC, Jules-Bertholet requested changes

2022-04-07 03:49 UTC, Jules-Bertholet commented on scripts/install
> +# FIND AND OPEN A PORT
We're not opening the port in the firewall, just using it internally

2022-04-07 03:49 UTC, Jules-Bertholet commented on README_fr.md
> +Photoview is a simple and user-friendly photo gallery that's made for photographers and aims to provide an easy and fast way to navigate directories, with thousands of high resolution photos.
Pour un README en français, c'e n'est pas très français…

2022-04-07 16:27 UTC, yalh76 commented on scripts/install
> +# FIND AND OPEN A PORT
yes, but it's the default title of this section...

2022-04-07 16:28 UTC, Jules-Bertholet approved these changes

2022-04-07 21:23 UTC, Jules-Bertholet approved these changes

2022-04-07 23:28 UTC, yalh76 commented
![image](https://user-images.githubusercontent.com/30271971/162335524-04d7c021-1611-4974-aa1d-21c2f32e4019.png)

![image](https://user-images.githubusercontent.com/30271971/162335554-bf86c7a9-76e7-4a67-9d2b-d474ebc965db.png)

2022-04-07 23:29 UTC, merged